# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='gmail_fb_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='special_admin',
            field=models.BooleanField(default=False),
        ),
    ]
