# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0003_auto_20161026_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('course', models.CharField(max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('a', models.CharField(max_length=100)),
                ('b', models.CharField(max_length=100)),
                ('c', models.CharField(max_length=100)),
                ('d', models.CharField(max_length=100)),
                ('e', models.CharField(max_length=100)),
                ('answer', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='questions',
            field=models.ManyToManyField(to='admin_interface.Question'),
        ),
    ]
