# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0008_feedback_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectiveAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_a', models.IntegerField(default=0)),
                ('count_b', models.IntegerField(default=0)),
                ('count_c', models.IntegerField(default=0)),
                ('count_d', models.IntegerField(default=0)),
                ('count_e', models.IntegerField(default=0)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_interface.Question')),
            ],
        ),
    ]
