# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0009_objectiveanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='students',
            field=models.ManyToManyField(to='admin_interface.Student'),
        ),
    ]
