# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0011_remove_question_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment', models.CharField(max_length=100)),
                ('submission_date', models.DateField()),
                ('submission_time', models.TimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_interface.Course')),
            ],
        ),
    ]
