# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0015_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='students',
        ),
    ]
