# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0016_remove_feedback_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='is_feedback',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='deadline',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_interface.Deadline'),
        ),
    ]
