# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0018_auto_20161101_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='deadline',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_interface.Deadline'),
        ),
    ]
